---
- name: Configure Docker Hosts
  hosts: dockerhosts
  become: true

  roles:
    - role: common
      tags:
        - common

    - role: users
      tags:
        - users

    - role: chrony
      tags:
        - chrony

    - role: docker
      tags:
        - docker

    - role: docker_compose
      tags:
        - docker_compose

- name: Test PROD failure notification
  ansible.builtin.fail:
    msg: "Testing Jenkins PROD failure notification"          
