---
- name: Configure Docker Hosts
  hosts: dockerhosts
  become: true

  roles:
    - role: common
      tags:
        - common

    - role: users
      tags:
        - users

    - role: chrony
      tags:
        - chrony

    - role: docker-test
      tags:
        - docker-test

    - role: docker_compose
      tags:
        - docker_compose
