---
common_packages:
  - vim
  - git
  - curl
  - wget
  - tree
  - htop
  - unzip
  - rsync

managed_users:
  - username: devops
    fullname: DevOps Administrator
    shell: /bin/bash
    sudo: true
    nopasswd: true

  - username: ansible
    fullname: Automation Account
    shell: /bin/bash
    sudo: false

chrony_servers:
  - time.google.com
  - time.cloudflare.com

# MariaDB Configuration
mariadb_database: ansible_lab
mariadb_user: ansible
