---
- name: Converge
  hosts: all
  become: true

  vars:
    mariadb_database: molecule_test
    mariadb_user: molecule
    vault_mariadb_password: molecule_password
    vault_mariadb_root_password: molecule_root_password
    docker_compose_verify_http: false

  roles:
    - role: docker_compose
